name: Docker Build

on:
  push:
    branches:
      - improvements-for-august  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Dockerfile
        run: |
          echo 'FROM node:lts' > Dockerfile
          echo 'WORKDIR /app' >> Dockerfile
          echo 'COPY package*.json ./' >> Dockerfile
          echo 'RUN yarn install' >> Dockerfile
          echo 'COPY . .' >> Dockerfile
          echo 'EXPOSE 3000' >> Dockerfile
          echo 'CMD ["yarn", "dev"]' >> Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/communitas-bidding-market:latest
